---
title: "Seminar 1.1: Core Tools"
subtitle: "LSE MY472: Data for Data Scientists"
date-modified: "30 September 2026"
date-format: "D MMMM YYYY"
format:
  html:
    embed-resources: true
    toc: true
    mathjax: true
execute:
  echo: true
  eval: false
---

This file will help you familiarise yourself with the core programming tools used in this course.

::: {.callout-warning}
## Code in this file will not run until you change global execution options

Every notebook in this course has `eval: false` set in its preamble, at the very top of the file. That tells Quarto **not** to run any of the code chunks when it compiles the document.

If you want your code to run, change that line to `eval: true` before you compile.
:::

## Required software

### Programming software

In this course, we will use the [Python programming language](https://www.python.org/) in the [Positron](https://positron.posit.co/) IDE (or, if you prefer, in [VS Code](https://code.visualstudio.com/)).

Python is a high level object-oriented programming language that is widely used for data science, scientific computing and general purpose software development.

Positron is an [integrated development environment (IDE)](https://en.wikipedia.org/wiki/Integrated_development_environment) that contains a suite of tools that are useful for coding in Python (as well as R). While it is possible to write and execute Python code directly in a **console** (for example, from the command line), an IDE offers a visually compelling environment for coding, with several enhancements built in, such as integration with GitHub, plot viewing tools, integrated help documentation, and much more.

Positron was developed by Posit, the same company that owns and develops [RStudio](https://posit.co/products/open-source/rstudio/), a popular IDE for R. Positron closely resembles Microsoft's [VS Code](https://code.visualstudio.com/), which is an "all purpose" IDE that is used for coding in a variety of programming languages and which is popular in industry. Either Positron or VS Code will work well for this course. Since many data scientists tend to use both Python and R, Positron offers a way to seamlessly go between these two languages within the same IDE.

You should install (or update) both Python and Positron. Full step-by-step instructions---including how to set up a virtual environment for this course---are in the course set up steps at <https://github.com/lse-my472/at26-getting-started>. You can install or update Python from <https://www.python.org/downloads/>. You can install or update Positron from <https://positron.posit.co/download.html>.

After you have installed/updated Python, please run the following line of code to make sure that you have a current version of Python.

```{python}
import sys
sys.version
```

You should be running Python 3.13.15. If your computer prints a different version number, please follow the course set up steps at <https://github.com/lse-my472/at26-getting-started>.

Within Python, you will need to install several **packages** (sometimes called **libraries**) that we will use in this course. Below, you will install some packages that we will use frequently.

### Other software

At times, you may be asked or prompted to install additional software that will be used for various topics in this course. For example, depending on the tools we use for web scraping, you may need to install a [Java Development Kit](https://www.oracle.com/java/technologies/downloads/).

We will also use [Git](https://git-scm.com/) (and [GitHub](https://github.com/)) in this course, which is described in more detail in the "Version control software" section below.

## Using Positron

Like VS Code (and other IDEs, like PyCharm), Positron is what's often referred to as a "project-based" IDE. This means that, in order to work in Positron, you usually need to open a directory inside Positron first, and _then_ navigate to the file you want from inside Positron. Contrast this with other "file-based" editors or apps, like Microsoft Word, where you can find a `.docx` file in your OS's file browser (Finder on macOS and File Explorer on Windows), double-click it, and it will appear as a stand-alone document in the app.

::: {.callout-note}
This is called "project-based" instead of "directory-based" because many IDEs create hidden files inside the working directory that contain settings and customisations that the user would like to use for all work inside that directory. Just keep in mind that "project-based" just means "directory-based".
:::

There are some pros and cons of project-based IDEs. One obvious advantage of using an IDE this way is that it mimics the way that you use the command line. Recall that whenever you are using the command line, you are always in a specific directory (called your working directory) and all the commands you use are being used inside that directory. This is the recommended workflow in project-based IDEs as well. It is important to know that this is now a common way for IDEs to work, and you should adapt your workflows to it (if you haven't already).

::: {.callout-tip}
This is why some IDEs will show you a security warning (like "Do you trust the person who made this file?") whenever you attempt to simply open a file into Positron directly from your OS file browser. This is a subtle reminder from the IDE that you should not be opening individual files directly into the IDE from the OS file browser, as it creates a security risk.
:::

The smoothest way to use Positron is to open the app directly, and then select "Open Folder..." from the File menu. This means that you should get into the habit of storing files in neatly organised directories that correspond to specific workspaces you want to work in. We will do some of this in seminars this term.

::: {.callout-important}
Because Python code has to be run by a specific Python installation, you also need to tell your IDE which **environment** to use---in IDE language, this is called selecting an **interpreter** (or sometimes a **kernel**). Once you have opened your course folder, use the command palette (`Shift+Command(⌘)+P` on macOS, `Ctrl+Shift+P` on Windows) and choose "Python: Select Interpreter", then select the one inside your course virtual environment. See the course set up steps for details. This is the single most common source of problems, so do not skip it.
:::

## Quarto

In this course, we will write Python code using notebooks. Specifically, we will use the [Quarto](https://quarto.org/) platform to do this. Like all notebooks, Quarto documents (`.qmd` files) are plain text files written in [markdown](https://en.wikipedia.org/wiki/Markdown), which is a simple formatting syntax to generate HTML or PDF documents. While markdown can be used in a variety of file types (including most notably `.md` files, like README files on GitHub), Quarto allows you to embed chunks of Python code (and other kinds of code!) that will run when you generate an HTML or PDF file.

The process of generating an HTML or PDF file from a Quarto document is called "compiling", "rendering", "knitting" or "previewing" it.[^1] We refer to these compiled HTML or PDF files as "knitted HTML/PDF", "rendered HTML/PDF" or "compiled HTML/PDF". You can render (and preview) a `.qmd` file in Positron using the `Preview` button in the toolbar at the top of the file editor. In this course, we will compile Quarto documents to HTML.

[^1]: The phrase "knitting" comes from R Markdown, which uses the "Knitr" engine to render documents. When a Quarto document contains Python code, Quarto instead uses the [Jupyter](https://jupyter.org/) engine to execute the code.

Using Python in a notebook has several advantages. First, it leaves an "audit trail" of your work, including documentation explaining the steps you made. This is helpful to not only keep your own progress organised, but also make your work reproducible and more transparent. Second, it provides confirmation that all of your Python code runs without any errors. If you are unable to compile your `.qmd` file to PDF or HTML, then that means there are bugs in your code (or bad markdown syntax) that you need to fix before you will be able to compile.

In MY472, you will get into the habit of using notebooks to demonstrate and document your work, including for the assessments.

### Quarto versus simple Python scripts

Quarto documents allow us to embed chunks of Python code into a notebook so that we can generate nice report-style documents that contain descriptive text, code and code output. Many people prefer not to embed their Python code in notebooks, and instead write simple Python scripts (`.py` files) that only contain Python code.

Either approach is acceptable for scientific computing. However, the work of a data scientist involves *communicating* the results of data analyses to wider audiences. This makes the notebook style of Python coding appealing for data scientists, and it is why we use it in this course.

### Quarto versus Jupyter notebooks

You may have used Jupyter notebooks (`.ipynb` files) in other courses. Quarto and Jupyter notebooks are very similar: both weave together descriptive text with executable chunks of code. In fact, Quarto uses the Jupyter engine to run the Python code in a `.qmd` file. The key difference is that a `.qmd` file is **plain text**, while an `.ipynb` file is a JSON file that also stores the code output. Plain text files work much better with Git---you can read a meaningful `git diff` of a `.qmd` file, but not of an `.ipynb` file---which is why we use Quarto in this course. You can read about how the two work together [here](https://quarto.org/docs/tools/jupyter-lab.html).

All of the MY472 course materials focused on Python coding will be provided in `.qmd` files.

## Markdown

The descriptive (non-code) text in a Quarto document is written using markdown, which is a kind of syntax that provides instructions for how the Quarto compiler should format the HTML or PDF document it creates. In combination with Python, it will generate a document that includes the comments, the Python code, and the output of running such code.

### Formatting text using markdown

You can review this `.qmd` file to get an idea of how markdown works. However, some common formatting you will use are given below:

###### Creates headlines of varying font sizes (with \# being the largest font size)

-   Creates bullet points

**Hello** or **hello** create bold text, and *world* or *world* italic text.

Or you can also add [hyperlinks](https://lse-my472.github.io/).

::: callout-warning
In a `.qmd` file, a hash (#) will create a heading, but *within* a code chunk (or in a `.py` file), it creates a code comment.
:::

## Embedding Python chunks

You can embed Python code in chunks like this one, which prints the result of two simple arithmetic problems.

```{python}
print(1 + 1)
print(2 - 2)
```

You can run a chunk of code on its own, by clicking the `Run Cell` button right above the chunk. You can also run all previous chunks by pressing `Run Above` or the next chunk by pressing `Run Next Cell`. In Positron, when you run code contained in a chunk, you will see the output of the code in the console below.

You can also run specific lines of code within a chunk by highlighting the line you want to run and then pressing `ctrl + enter` in Windows or `command(⌘) + enter` in macOS.

You can also include plots and graphics in chunks, for example the following simple scatterplot.

```{python}
import matplotlib.pyplot as plt
x = [1, 3, 4, 5]
y = [2, 6, 8, 10]
plt.scatter(x, y)
plt.show()
```

If you run this chunk of code in Positron (for example, by pressing `Run Cell`), the plot will be generated inside the PLOTS panel on the bottom right corner. (Note: The first time you run the chunk above, it may take a minute and display the following: `Matplotlib is building the font cache; this may take a moment.`)

There are lots of options and customisations that you can set for each Python code chunk you include in a Quarto document. For example, for really long and complex notebooks, it is often useful to provide labels for each chunk of code. For example, the following chunk of code is labelled "hello-chunk".

```{python}
#| label: hello-chunk
z = "Hello!"
```

There are several reasons you might want to label chunks of code, but we will not do it much in MY472. A full list of the various options and customisations available for Python code chunks can be found at <https://quarto.org/docs/reference/cells/cells-jupyter.html>.

### Side note on method chaining

We will assume all students have familiarity with core Python coding skills, including Python syntax. One thing you will see often in the code in this course is **method chaining**, which is a way of writing a series of operations by attaching each method call directly to the result of the previous one using dots.[^2] You do not need to chain methods in your own code, but as an aspiring data scientist, you should become comfortable enough with it to engage with the code from this class.

[^2]: If you have used R, method chaining is Python's rough equivalent of piping syntax (`|>` or `%>%`). Note that chaining only works when each step returns an object that has the next method available on it.

Consider a simple example of two ways of doing the same thing, one without chaining and one with chaining.

```{python}
# Without chaining
x = "  Hello world!  "
x = x.strip()
x = x.upper()
print(x)

# With chaining
print("  Hello world!  ".strip().upper())
```

You will not see a lot of method chaining until we introduce tabular data in a future week.

## Execution options

A major theme in this course is reproducibility. In part, this entails setting up your workflow so that others can easily engage with your work product and re-run your code without errors and without excessive runtimes, excessive computational burdens and/or repetitive code. For example, another user (or a course instructor) should be able to copy your `.qmd` file(s) to their own machine and recompile them easily.

One important factor in the reproducibility pipeline for notebooks is **execution options**. Recall that you compile an HTML or PDF document with all the formatted text, code, code comments, and output from your entire `.qmd` file by clicking on `Preview`. Quarto's [execution options](https://quarto.org/docs/computations/execution-options.html) give instructions to the Quarto compiler about how to handle the code chunks.

There are three major execution options you will use most frequently:

-   `eval` determines whether a chunk of code is executed during the compiling process
-   `echo` determines whether a chunk of code is printed in the compiled HTML/PDF
-   `output` determines whether the output of an executed code chunk is printed in the compiled HTML/PDF

Execution options can be set to be either `true` or `false` by writing, for example, `eval: true`. (Note: if you set `eval: false` then the `output` option does not do anything as there is no code output.) Moreover, execution options can be set either globally (for the whole notebook) or locally (for a specific chunk). Here is an example of a code chunk with local execution options, which tells the Quarto compiler not to print the code, but to evaluate it anyway and print the output.

```{python}
#| echo: false
#| eval: true
#| output: true
print("The code for this chunk is hidden, but the output is not!")
```

::: callout-note
If you have experience with R Markdown, note that R Markdown allows you to specify chunk options inside the curly brackets, e.g. ```` ```{r, echo=FALSE, eval=TRUE} ````. Quarto instead uses the `#|` comment syntax shown above, and for Python chunks this is the only syntax that works.
:::

In the chunk above, we have defined `echo`, `eval` and `output` locally (i.e., for that chunk individually). You can also set these options globally, i.e. for all chunks in the entire document. To do this, you set the options in the document's preamble. Notice that this `.qmd` document has set `echo: true` and `eval: false`, which means that the default for all chunks is to print the code, but not evaluate it. When you set execution options locally (inside a chunk), this will override whatever global options you set in the preamble. If no execution options are set globally or locally, then Quarto will use its own default configuration which includes `echo: true`, `eval: true` and `output: true`.

::: callout-tip
In this course, Quarto documents will be set up with global execution options in the preamble. When you download a `.qmd` file to your own computer and begin working with it, you may wish to alter these settings.
:::

See [here](https://quarto.org/docs/computations/execution-options.html) for a list of code chunk execution options you can provide in Quarto, such as `echo` and `eval`. See [here](https://quarto.org/docs/computations/python.html) for a discussion of how Quarto executes Python code.

## Installing packages

There are a large number of **packages** (sometimes called **libraries**) available for the Python programming language. A package is a bundle of files---mostly `.py` scripts---that another person developed and then made available to Python users via the [Python Package Index (PyPI)](https://pypi.org/). A single `.py` file inside a package is called a **module**. Packages contain functions, classes and other objects that help you do useful things in Python.

Packages are sometimes referred to as "wrappers" because they typically involve making existing Python functions and objects more pleasant and easier to use for a specific purpose. In other words, they *wrap around* existing Python functions to provide a cleaner user experience. You will also often hear people refer to the **standard library**, which is a reference to all the packages that ship with Python itself (such as `os`, `re` and `json`) and which you can use without installing anything.

::: {.callout-note}
## "Package" and "module" in practice

In this course we use **package** for anything you install and import, and **module** for a single `.py` file inside one. That is how the words are used in most everyday conversation. Python's own documentation is stricter, though, and you will meet the stricter senses as soon as you read it:

-   A **module** is one file of Python code that you can import. `os` really is a single file, `os.py`.
-   A **package**, strictly speaking, is a *directory* of modules with an `__init__.py` file inside it, which is what lets you write dotted names like `json.decoder` or `numpy.linalg`. `re`, `json`, `pandas` and `numpy` are all packages in this sense.
-   In a third sense, what you `pip install` from PyPI is a **distribution package**, whose name need not match what you import: `pip install beautifulsoup4` gives you `import bs4`.

So `os` is, strictly, a module and not a package---even though it ships in the standard library alongside packages like `re`. Nothing turns on this when you write code, since you `import` both the same way. But it explains why you will see the same things called by different names, and why the error Python raises when an import fails is `ModuleNotFoundError` even when what is missing is an entire package you forgot to install.
:::

In this course, we'll use many Python packages that are useful for various data science tasks. As you might imagine, since Python packages are developed by Python users, some of them are better and more reliable than others. When we need to rely on Python packages, the instructors of this course have tried to find and integrate the most commonly used and stable packages available. That said, you will likely notice some occasional bugs, which is a fact of life for programmers!

You can see what Python packages are already installed in your environment by running the following.

```{python}
from importlib.metadata import distributions
sorted(d.metadata["Name"] for d in distributions())
```

If you want to check if a specific package is installed, you can do the following.

```{python}
"MY472" in [d.metadata["Name"] for d in distributions()] # Not a package, so it should return False!
```

### The core packages for this course

The packages we will use *a lot* in this course are:

-   [`os`](https://docs.python.org/3/library/os.html): for working with file paths and directories (standard library)
-   [`re`](https://docs.python.org/3/library/re.html): for working with character strings using regular expressions (standard library)
-   [`pandas`](https://pandas.pydata.org/): for tabular data manipulations
-   [`numpy`](https://numpy.org/): for numerical arrays and mathematical operations
-   [`matplotlib`](https://matplotlib.org/): for plotting data

The first two are in Python's standard library, so they are already on your computer. You just `import` them. The rest come from `requirements.txt`, which pins the exact version of every package. Each week's seminar repository has its own. Week 1's is the one already in your `LSE-MY472-AT26` folder from set up.

To install, open the terminal in Positron (**Terminal → New Terminal**), check the prompt starts with `.venv`, go to the folder with that `requirements.txt`, and run this command.

```
python -m pip install -r requirements.txt
```

::: callout-important
In a virtual environment defined by a `requirements.txt`, **never install anything outside that file** --- not by naming a package, and not with `--upgrade`. The file is what makes your environment reproducible: it is how anyone rebuilds exactly your setup. Install something it does not list and it stops describing your environment, which defeats the point. New package? Add it to the file first.
:::

::: callout-note
Unlike in R, you install packages from the terminal rather than from inside a code chunk. This stops your notebook from silently changing another user's environment when they run it.
:::

::: callout-warning
Always install into the virtual environment you made for this course. Install into your computer's system-wide Python by accident and your notebooks will fail to find the packages---raising `ModuleNotFoundError`---even though `pip` said the install succeeded.

This is why we write `python -m pip` rather than plain `pip`. `pip` is itself a Python package, and `python -m pip` means "run `pip` using *this* Python", so there is no doubt which installation you are adding to. Most machines let you type `pip` as a shortcut; if you do, be certain you have activated the environment you mean to install into.
:::

You can also check whether you have the most recent version of a package as follows (here, `pandas`).

```{python}
from importlib.metadata import version
version("pandas")
```

## Version control software

In this course, we will use [Git](https://git-scm.com/), which is the most popular distributed version control system (VCS) in the world. Git can be used to archive and track versions of code, share code with multiple users (or disseminate publicly), manage edits made by a large number of individuals, and back up code to the cloud (i.e., at [GitHub.com](https://github.com/)). In this course, we will use Git in a fairly basic way. Students will use it to turn in their coursework, and to retrieve course materials. We will also, on occasion, require students to use it to back up their work to GitHub, and we strongly encourage all students to do this regularly with their course materials.

### What are Git and GitHub?

Git is **version control system (VCS)** software that allows you to keep records of file changes: _who_ made _which_ changes _when_. In addition to keeping a record of file changes, it has tools for managing conflicting versions (e.g., different users making changes to the same file), etc. In MY472, you will mostly use Git to track your own changes to your own files, so we will not spend a lot of time on the Git tools for managing collaboration across users.

You usually use Git to track the versions of your files in each project. In programming and data science contexts, a **project** is contained within a specific directory. So, the term "project" is often used as shorthand for a specific directory that contains a set of files and subdirectories used for a real-world project (like a course, or a paper, or a piece of software). A project that uses Git to track file versions is call a **repository** or a **repo**.

GitHub is a cloud storage service that is designed to work seamlessly with Git. Think of GitHub as "Dropbox for coders and data scientists". There are many features on GitHub, but the obvious core feature is to keep copies of your repos in the cloud. As discussed in lecture, we refer to directories on your computer as "local" and directories elswhere as "remote" --- so we will often refer to your "local repo" when talking about a Git repo on your computer, and the "remote repo" (or just "remote") when talking about the copy of your repo as it exists on GitHub's servers.

Tracking versions and syncing to the cloud are not automatic with Git/GitHub as they are with Dropbox. There is a reason for this, but we will not discuss it in detail. You just need to keep on top of:

1. Tracking your file versions with Git.
2. Syncing your local repo to GitHub (and vice versa).

#### Tracking versions

In Git, a specific version of a file is called a **commit**. When you "commit" a file, you are marking the current version as one of the versions you store in the repo history. The more often you commit, the more versions you will track, and the more flexibility you have to roll back changes if you want to go back to a previous version.

In order to make a new commit of a file, you need to use the Git software. A common way to use Git is by using the CLI for Git which is called `git`. To make a new commit of a file you do run these two commands at the command line (assuming you are inside a Git repository): `git add <path to file>` and then `git commit -m "Brief description"`. The first step will **stage** your file, and the second one creates the commit and adds a brief description of the commit. When making your commit messages, be brief and informative. Commits with descriptions like "make some changes" or "edit files" are bad because they do not explain what the core changes were in the commit. Better to write things like "fixed FileNotFound error in line 24".

You can also stage and commit multiple files at once by listing all the files after `git add`, separating the path to each file with a space. You can also do `git add .` which uses a dot to indicate that all files with any changes should be staged for commit. This is dangerous, though, since you may end up committing files you did not intend to commit.

At any point in time, you can get the full history of commits in a Git repo by using `git log`, which will print each commit, showing its unique ID number (it's **hash**), the author of the commit, the date the commit was made, and the brief description you made with the commit.

#### Syncing to GitHub

Any file with commits can be synced to GitHub, assuming that your local repo has been set up to be connected to a remote copy on GitHub. (We'll show you how to do this in the seminar.) Assuming this is the case, then when you want to sync you either use `git push` (send your local changes to remote) or `git pull` (bring remote changes to local). The Git software will detect any new commits and send them over the network in the direction you indicated (`push` to remote, `pull` from remote).

In this course, you will mostly start by working with local files that you then push to GitHub. Pulling is more important when active commits are being made across several machines. For example: (1) you have two machines, so you push new commits from machine 1 to remote and then pull those changes to machine 2; (2) you modify a file directly on GitHub website and need to pull the changes to your local copy; or (3) multiple people are actively working on a file on different computers, pushing changes, and you need to bring the most recent version to your machine.

As you can imagine, things can get really tricky when trying to manage files that are being modified by many people at once. This is somewhat beyond the scope of MY472.

#### Setting up your repo

Again, a repo is just a directory on a computer that is treated like a "project" and has been set up to work with Git. A directory can be converted into a Git repo by **initialising** it with `git init`. This will create a hidden subdirectory called `.git` inside the project directory. This hidden folder is where the database of all the commits is stored. If you delete this hidden folder, you are turning the directory back into a regular directory (no longer a repo).

You will almost never use `git init` in MY472 for reasons we will not discuss in any detail. So, the way you will create a new repo on your computer is by: (1) initialising a new repo on remote (i.e., on GitHub), and then (2) **cloning** this remote repo to your computer (local). When you do this, the Git software downloads a copy of the repo as it exists on GitHub and puts the contents into a folder on your machine along with a hidden `.git` folder that means it is a repo.

The way you do this is by: (1) in the terminal, navigate to the directory where you want the repo (such as `~/LSE-MY472-AT26`), (2) on GitHub copy the remote repo's clone URL, and (3) using the terminal, execute the command `git clone <clone URL>`.

::: {.callout-note}
In MY472, we create new repos with `git clone` from remote to local instead of `git init` so that the Git software takes care of configuring the link between the local and remote copies. There is a way to make a repo locally, then do `git init` and then push it to remote; but it's a little more fiddly.
:::

Git will track versions of any file inside a repo. The software pays attention to when files are modified by you, and whether you have committed those changes or not. You can always use `git status` to see the status of your repo, including whether you need to stage and commit any new edits.

There are some files you will store in a Git repo that you do NOT want Git to track or sync for you. For example, project files with sensitive information. You can create a (hidden) plain text file called `.gitignore` inside the Git repo and list every file you do not want tracked inside the file (one per line). The Git software knows to read this file and ignore any file that is listed on it.

### Registering for a GitHub account

To take full advantage of the Git VCS, you will need a GitHub account. You can think of GitHub as the cloud-based storage system for code and other data that users are developing and tracking using Git. In addition to being a cloud storage website, it also offers a wide range of other tools that help users collaborate and disseminate their code.

For this course, you must use an anonymised account. Please create a username in the format **LSE-XXXXX-2627** where **XXXXX** is your LSE candidate number (NOT your student ID number!), and **-2627** indicates the academic year.

::: callout-warnings
You should be sure to link your GitHub account to your LSE email address during account registration, as you may not be able to access some of the course materials with a GitHub account that is not connected to an LSE email address.
:::

You can register for a new GitHub account at <https://github.com/>

### Claiming education benefits

GitHub has several tiers of membership that come with different benefits, such as unlimited repositories, more cloud storage, etc. GitHub offers an elevated membership tier for affiliates of universities, which is called GitHub Education. You may need some of the benefits of this elevated membership tier while you are at LSE, so we strongly recommend you apply for student benefits via <https://github.com/education/students>.